### ISSUE TITLE
Lets create an issue

### ISSUE THREAD

**Issue by johnklima** [johnnynilsen/REcycle#1]
bug/feature tracking is very useful in the course of development and all software companies use it. It is very important to get in the habit of reporting/opening issues, fixing, and closing them within the SCM (source control management) system and github includes this ability.  So have a look the issues feature of github! Even if you are a small team, or solo, it is nice to remind yourself what the state of affairs is. Some familiarity will help you in a job interview!!

**Comment by johnklima** [comment]
let's see if you notice this, upon which time simply close the issue with a comment.

**Comment by johnnynilsen** [comment]
Issue has been noticed and closed.
